// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeHO5digHPfuBvYEHBMfqQnybI2V36FHc',
    appId: '1:552061866314:android:d1b0204968603ba532f1b3',
    messagingSenderId: '552061866314',
    projectId: 'todo-list-provider-eb3ca',
    storageBucket: 'todo-list-provider-eb3ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc66iI9H8YwYPSoxOTxUKvfSJenK02Ha0',
    appId: '1:552061866314:ios:7cc90049bc16f64a32f1b3',
    messagingSenderId: '552061866314',
    projectId: 'todo-list-provider-eb3ca',
    storageBucket: 'todo-list-provider-eb3ca.appspot.com',
    androidClientId: '552061866314-3bn8dbsfgaiatot0vinj5861tg0i66k4.apps.googleusercontent.com',
    iosClientId: '552061866314-d4luk6t1fi308h8aucce2k6htcvi2jkm.apps.googleusercontent.com',
    iosBundleId: 'br.com.fabriciosuhet.todoListProvider',
  );
}
